### ISSUE TITLE
how to access airflow web

### ISSUE THREAD

**Issue by markqiu** [mumoshu/kube-airflow#12]
as mentioned in the readme, use make web-browse to access airflow web interface. but the I checked the Makefile, this just start minikube command which confuses me:
minikube service web -n $(NAMESPACE)

so my question is how to access the airflow web interface from a remote machhine not in a minikube environment? Thank you.

**Comment by rolanddb** [comment]
@markqiu You can use portforwarding.

First find the pod name:
    kubectl get pods

Then forward the port:
    kubectl port-forward web-4130159376-46z6r 8080

Then open localhost:8080 in your browser.

**Comment by markqiu** [comment]
thank you very much! @rolanddb

**Comment by gsemet** [comment]
Can you update the README for that?

**Comment by raam86** [comment]
You may also use ingress. Make sure you have that addon in minikube
```
    web:
     nginx.ingress.kubernetes.io/app-root: /airflow
      # Example for Traefik:
      # traefik.frontend.rule.type: PathPrefix
      # kubernetes.io/ingress.class: traefik

    flower:
    #   traefik.frontend.rule.type: PathPrefix
    #   kubernetes.io/ingress.class: traefik
     nginx.ingress.kubernetes.io/app-root: /airflow/flower

  # hostname for both endpoint
  host: "k8.etl"
  path:
    # if web is '/airflow':
    #  - UI will be accessible to '/airflow/admin'
    #  - Healthcheck is at 'http://mycompany.com/airflow/health'
    #  - api is at 'http://mycompany.com/airflow/api'
    web: /airflow
    # if flower is '/airflow/flower':
    #  - api is at 'http://mycompany.com/airflow/flower'
    flower: /airflow/flower
```
Flower doesn't really work yet
