### ISSUE TITLE
Using external databse.

### ISSUE THREAD

**Issue by rohithzr** [mumoshu/kube-airflow#48]
I want to use an external database like RDS for airflow, but I think it's hardcoded to `postgres:5432`, is there a way to override this?

**Comment by rohithzr** [comment]
I have tried adding 
```
env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: POSTGRES_HOST
          value: myAirflowHost
        - name: POSTGRES_USER
          value: myAirflowUser
        - name: POSTGRES_PASSWORD
          value: myAirflowPass
        - name: POSTGRES_CREDS
          value: myAirflowUser:myAirflowPass
```
